### ISSUE TITLE
{"Fault":{"Error":[{"Message":"Required param missing, need to supply the required value for the API","Detail":"Required parameter ExpenseAccountRef or IncomeAccountRef is missing in the request","code":"2020"}],"type":"ValidationFault"}

### ISSUE THREAD

**Issue by jefferyasharp** [IntuitDeveloper/SampleApp-TimeTracking_Invoicing-DotNet#1]
The sample is missing code for setting theses parameters, and there is no documentation on how to implement it. Syncing item data does not work out of the box. The AccountRef must be set.

Please Assist

**Comment by smathilakath** [comment]
Thank you for raising the issue. I want to bring your kind notice that the sample app is not broken with default parameter unless you change the specific parameter. In the current instance you are trying to add ExpenseAccountRef. The idea behind writing a sample app is just give an overview of how data can be pushed in to QBO System. I am attaching the screen shot of the operations performed.

![sync](https://cloud.githubusercontent.com/assets/9986042/9060555/9f6ab88a-3ad2-11e5-8650-46d359efbd0b.JPG)
![invoice generation](https://cloud.githubusercontent.com/assets/9986042/9060557/a27eed02-3ad2-11e5-919e-17583d8c3e37.JPG)
![invoice param](https://cloud.githubusercontent.com/assets/9986042/9060560/a6de8362-3ad2-11e5-857f-2e9a005ca1a9.JPG)

Please observe the Invoice parameter. You need to go to api explorer and try your requirement which match the request and try to simulate to avoid api related issues.

Link : https://developer.intuit.com/v2/apiexplorer?apiname=V3QBO#?id=Invoice

Note :  givenName = '{0}' and familyName = '{1}' is considered as based to determine whether data is synced.

**Comment by jefferyasharp** [comment]
Thanks for the quick response, however all I have done is followed these steps

1.Clone the GitHub repo to your computer
2.Fill in your Configuration file values ( consumer key, consumer secret) by copying over from the keys section for your app.
3.Enable logging in the config file by updating the path.
4.Open the project from Visual Studio (VISUAL STUDIO 2015)
5.Populate the data in to tables from /Scripts folder (DID NOT UGRADE DATA FILE, INSTALLED SQL SERVER LOCALDB 2012)

I build and run the solution

Connect to QuickBooks is successful
Sync Customers Successful
Sync Employees Successful
Sync Items _Error

![s1](https://cloud.githubusercontent.com/assets/4176349/9065337/c0ce06d2-3a85-11e5-8744-b52131a9518b.jpg)


![s2](https://cloud.githubusercontent.com/assets/4176349/9065407/14dda12e-3a86-11e5-91f7-0d67829cac7f.jpg)

**Comment by jefferyasharp** [comment]
Intuit.Ipp.Exception.IdsException was unhandled by user code
  ErrorCode=400
  HResult=-2146233088
  Message=BadRequest
  Source=System
  StackTrace:
       at Intuit.Ipp.DataService.DataService.Add[T](T entity)
       at TimeTracking.Models.SyncService.SyncServiceItems(Object controller, Syncdto syncObjects) in C:\Users\jeffe\Source\SavoyEventStaff\TimeTracking\Models\Service\SyncService.cs:line 251
       at TimeTracking.Controllers.SyncController.ServiceItem(Int64 id) in C:\Users\jeffe\Source\SavoyEventStaff\TimeTracking\Controllers\SyncController.cs:line 102
       at lambda_method(Closure , ControllerBase , Object[] )
       at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
       at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
       at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
       at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
       at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
       at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
       at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
       at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
       at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
  InnerException: 
       HResult=-2146233088
       Message=ValidationException was thrown.
       InnerException:

**Comment by mark-truran** [comment]
I had the same problem. A quick work around. 

1. Start project.
2. Click on the button that reads 'View in QuickBooks' which is above the table of Service Items
3. When QuickBooks opens, add a new ServiceItem (Machines, 100).
4. Stop and re-start project.

Step 3 fixes the problem you are having. 

![screenshot](https://cloud.githubusercontent.com/assets/13332188/9309426/78e1df66-4501-11e5-9578-451676f15680.png)

**Comment by mark-truran** [comment]
The reason:

If the Machines service item does not exists in the sandbox, then this code

Item resultFound = queryService.ExecuteIdsQuery(EXISTING_ITEM_QUERY).FirstOrDefault<Item>();
                    if (resultFound == null)
                    {
                        Item entity = dataService.Add<Item>(ItemItem);
                        syncObjects.QboId = entity.Id;
                        syncObjects.IsServiceItemSync = true;
                    }

will throw an exception. Reason., you cannot ADD a new service item without supplying an expense account ref or income account ref:

{"Fault":{"Error":[{"Message":"Required param missing, need to supply the required value for the API","Detail":"Required parameter ExpenseAccountRef or IncomeAccountRef is missing in the request","code":"2020"}],"type":"ValidationFault"},"time":"2015-08-17T09:02:23.585-07:00"}

This seems to be expected behaviour.

**Comment by smathilakath** [comment]
Yes. This is a bug. I am fixing it. 

Thanks for the guidance. @mark-truran
